name: Pixel and Code
favicon: null
layout_spectrum: 0.6904447127599269
typography_spectrum: 0.4777291619684547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.60968964593485
  lightness: 0.8190544180106372
  saturation: 0.5979282099287957
  rhythmicContrast: 0.9410389764234424
purpose: []
